name = "VofiJul"
uuid = "e4b0aab4-58c8-425b-9d4c-54271c2045d0"
authors = ["libat"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Vofinit = "1beee101-8e09-4165-b3f9-a3e33534e38b"

[compat]
BenchmarkTools = "1.6.3"
SpecialFunctions = "2.6.1"
StaticArrays = "1.9.15"
Test = "1.11.0"
